runtime: php83

env_variables:
  APP_ENV: 'dev'
  APP_SECRET: '4fd7f408402098ffe6c59ca11af9aa0d'
  DATABASE_URL: 'pgsql://postgres:postgres@104.155.20.123:5432/db?unix_socket=/cloudsql/serverless-4al:europe-west1:admin'

automatic_scaling:
  max_instances: 1

instance_class: F2

entrypoint: serve public/index.php

runtime_config:
  document_root: public
